CREATE DATABASE IF NOT EXISTS the_bookworm;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE library (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  book_id VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  authors VARCHAR(100) NOT NULL,
  thumbnail VARCHAR(2000) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id)
    REFERENCES users(id)
);